spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prestamosdb?useSSL=false&serverTimezone=UTC
    username: jose
    password: miriam
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
