server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librosdb?useSSL=false
    username: jose
    password: miriam
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true