server:
  port: 7070

spring:
  application:
    name: jhm-config-server
  cloud:
    config:
      server:
        git:

          uri: https://github.com/cher-yami/JOSE.git
          searchPaths: config-data
          default-label: main
  security:
    user:
      name: jose
      password: miriam





